title: Xingyue Wang's Homepage
page-top-title: Xingyue Wang
top-section-bg-text: Computer Science
home-subtitle: Xingyue Wang&ensp;|&ensp;王星越
copyright-text: '&copy; Sen Li 2023-2026. All Rights Reserved.'
