title: Xingyue Wang's Homepage
page-top-title: Xingyue Wang
top-section-bg-text: Computer Science
home-subtitle: Xingyue Wang&ensp;|&ensp;王星越
copyright-text: '&copy; Xingyue Wang 2026-2126. All Rights Reserved.'
